resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: scitixai/arks-operator
  newName: registry-ap-southeast.scitix.ai/k8s/arks_pr
  newTag: v1.0-d701270
